//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJApp_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dj
    {
        public string DjId { get; set; }
        public string DjUserId { get; set; }
        public string SpotifyUserName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> AgreedToTerms { get; set; }
        public Nullable<bool> QuedUp { get; set; }
        public string DJName { get; set; }
    }
}
