//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJApp_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string LocationId { get; set; }
        public string LocationName { get; set; }
        public string PlaylistId { get; set; }
        public string SpotifyPlayListId { get; set; }
        public string SongCurrentlyPlayId { get; set; }
        public string SongCurrentlyPlayingSpotifyId { get; set; }
        public string Token { get; set; }
        public string SportifyUserName { get; set; }
        public string SpotifyDeviceId { get; set; }
        public string LocationOwnerId { get; set; }
    }
}
