//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJApp_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelayOrder
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> RelayDate { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EnteredLocationDate { get; set; }
        public Nullable<int> RelayOrder1 { get; set; }
        public string PlaylistId { get; set; }
        public Nullable<int> MaxPlays { get; set; }
        public Nullable<int> Selected { get; set; }
        public Nullable<bool> NextInQue { get; set; }
        public Nullable<int> ProcessCount { get; set; }
        public string LocationId { get; set; }
    }
}
