//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJApp_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public string SongId { get; set; }
        public string PlaylistId { get; set; }
        public string SongTitle { get; set; }
        public string SongArtist { get; set; }
        public string SongSelector { get; set; }
        public Nullable<System.DateTimeOffset> PlayedDate { get; set; }
        public string LocationId { get; set; }
        public string SpotifyId { get; set; }
        public Nullable<int> PlayListPosition { get; set; }
    }
}
